source 'https://cdn.cocoapods.org'



platform :ios, '12.0'

target 'DJBusinessModuleSwift_Example' do
  use_frameworks!
  use_modular_headers!
  pod 'DJBusinessModuleSwift', :path => '../'

  #pod 'YYCache', :git => 'git@github.com:ibireme/YYCache.git'
  pod 'RXNetworks', :modular_headers => true

  # target 'DJBusinessModuleSwift_Tests' do
  #   inherit! :search_paths
  # end
end
