use_frameworks!

platform :ios, '11.0'

target 'DJBusinessModuleSwift_Example' do
  pod 'DJBusinessModuleSwift', :path => '../'

  target 'DJBusinessModuleSwift_Tests' do
    inherit! :search_paths

    
  end
end
